.TH "App\Models\UserIdentity" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\UserIdentity
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcasts\fP ()"
.br
.ti -1c
.RI "\fBuser\fP ()"
.br
.ti -1c
.RI "\fBaddress\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\UserIdentity::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'nik',
        'full_name',
        'id_card_image'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
