.TH "App\Services\DonationService" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Services\DonationService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdonateProduct\fP (array $donationData)"
.br
.ti -1c
.RI "\fBdonateFund\fP (array $donationData)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateBookItemPivot\fP (\fBProductDonation\fP $donation, \fBDonationItem\fP $donationItem, array $bookData)"
.br
.ti -1c
.RI "\fBcreateFacilityItemPivot\fP (\fBProductDonation\fP $donation, \fBDonationItem\fP $donationItem, array $facilityData)"
.br
.ti -1c
.RI "\fBcreateDonationItem\fP (\fBDonorDonation\fP $donation, array $donationData)"
.br
.ti -1c
.RI "\fBattachDonationToDonor\fP (\fBDonor\fP $donor, \fBDonation\fP $donation)"
.br
.ti -1c
.RI "\fBgetDonorDonationPivot\fP (\fBDonor\fP $donor, \fBDonation\fP $donation)"
.br
.ti -1c
.RI "\fBstoreImage\fP (string $title, UploadedFile $file, string &$filepath)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
