.TH "App\Http\Resources\Donation\DonationResource" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Resources\Donation\DonationResource
.SH SYNOPSIS
.br
.PP
.PP
Inherits JsonResource\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtoArray\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Resources\\Donation\\DonationResource::toArray (Request $request)"
Transform the resource into an array\&.

.PP
\fBReturns\fP
.RS 4
array<string, mixed> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
