.TH "App\Models\Book" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\Book
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcasts\fP ()"
.br
.ti -1c
.RI "\fBdonations\fP ()"
.br
.ti -1c
.RI "\fBslug\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'books'"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\Book::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'isbn',
        'title',
        'authors',
        'published_year',
        'synopsis',
        'cover_image',
        'price'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
