.TH "App\Http\Controllers\ProfileController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers\ProfileController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Http\\Controllers\\Controller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBedit\fP (Request $request)"
.br
.ti -1c
.RI "\fBupdate\fP (\fBProfileUpdateRequest\fP $request)"
.br
.ti -1c
.RI "\fBdestroy\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Controllers\\ProfileController::destroy (Request $request)"
Delete the user's account\&. 
.SS "App\\Http\\Controllers\\ProfileController::edit (Request $request)"
Display the user's profile form\&. 
.SS "App\\Http\\Controllers\\ProfileController::update (\fBProfileUpdateRequest\fP $request)"
Update the user's profile information\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
