.TH "App\Http\Controllers\Auth\EmailVerificationPromptController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers\Auth\EmailVerificationPromptController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Http\\Controllers\\Controller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__invoke\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Controllers\\Auth\\EmailVerificationPromptController::__invoke (Request $request)"
Display the email verification prompt\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
