.TH "App\Providers\AppServiceProvider" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Providers\AppServiceProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBboot\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Providers\\AppServiceProvider::boot ()"
Bootstrap any application services\&. 
.SS "App\\Providers\\AppServiceProvider::register ()"
Register any application services\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
