.TH "App\Http\Requests\ProfileUpdateRequest" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Requests\ProfileUpdateRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherits FormRequest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrules\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Requests\\ProfileUpdateRequest::rules ()"
Get the validation rules that apply to the request\&.

.PP
\fBReturns\fP
.RS 4
array<string, \\Illuminate\\Contracts\\Validation\\ValidationRule|array<mixed>|string> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
