.TH "App\Http\Controllers\Fund\FundController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers\Fund\FundController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Http\\Controllers\\Controller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (Request $request)"
.br
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBshow\fP (\fBFund\fP $fund)"
.br
.ti -1c
.RI "\fBsubmitFund\fP (\fBMidtransService\fP $service)"
.br
.ti -1c
.RI "\fBnotificationHandler\fP (Request $request)"
.br
.ti -1c
.RI "\fBfinish\fP (Request $request)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$request\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "App\\Http\\Controllers\\Fund\\FundController::__construct (Request $request)"
Class constructor\&.

.PP
\fBParameters\fP
.RS 4
\fI$request\fP User Request
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Controllers\\Fund\\FundController::index ()"
Show index page\&.

.PP
\fBReturns\fP
.RS 4
\\Illuminate\\View\\View 
.RE
.PP

.SS "App\\Http\\Controllers\\Fund\\FundController::notificationHandler (Request $request)"
Midtrans notification handler\&.

.PP
\fBParameters\fP
.RS 4
\fI$request\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "App\\Http\\Controllers\\Fund\\FundController::show (\fBFund\fP $fund)"
Show Snap UI Page\&.

.PP
\fBReturns\fP
.RS 4
redirect 
.RE
.PP

.SS "App\\Http\\Controllers\\Fund\\FundController::submitFund (\fBMidtransService\fP $service)"
Submit fund\&.

.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
