.TH "App\Http\Resources\Donation\DonationCollection" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Resources\Donation\DonationCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherits ResourceCollection\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtoArray\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Resources\\Donation\\DonationCollection::toArray (Request $request)"
Transform the resource collection into an array\&.

.PP
\fBReturns\fP
.RS 4
array<int|string, mixed> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
