.TH "App\Models\DonorDonation" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\DonorDonation
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdonor\fP ()"
.br
.ti -1c
.RI "\fBdonation\fP ()"
.br
.ti -1c
.RI "\fBdonationItem\fP ()"
.br
.ti -1c
.RI "\fBfunds\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcasts\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'donor_donation'"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\DonorDonation::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'donor_id',
        'donation_id',
        'verified_at'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
