.TH "App\Http\Middleware\HandleInertiaRequests" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Middleware\HandleInertiaRequests
.SH SYNOPSIS
.br
.PP
.PP
Inherits Middleware\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBversion\fP (Request $request)"
.br
.ti -1c
.RI "\fBshare\fP (Request $request)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$rootView\fP = 'app'"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Middleware\\HandleInertiaRequests::share (Request $request)"
Define the props that are shared by default\&.

.PP
\fBReturns\fP
.RS 4
array<string, mixed> 
.RE
.PP

.SS "App\\Http\\Middleware\\HandleInertiaRequests::version (Request $request)"
Determine the current asset version\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
