.TH "App\Models\BookDonation" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\BookDonation
.SH SYNOPSIS
.br
.PP
.PP
Inherits Pivot\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbook\fP ()"
.br
.ti -1c
.RI "\fBdonation\fP ()"
.br
.ti -1c
.RI "\fBdonationItem\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'book_donation'"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\BookDonation::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'donation_id',
        'isbn',
        'status'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
