.TH "App\Http\Controllers\Auth\EmailVerificationNotificationController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers\Auth\EmailVerificationNotificationController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Http\\Controllers\\Controller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController::store (Request $request)"
Send a new email verification notification\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
