.TH "App\Models\DonationItem" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\DonationItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdonorDonation\fP ()"
.br
.ti -1c
.RI "\fBbooks\fP ()"
.br
.ti -1c
.RI "\fBfacilities\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'donation_items'"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\DonationItem::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'package_picture',
        'resi',
        'status'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
