.TH "App\Http\Controllers\Auth\NewPasswordController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers\Auth\NewPasswordController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Http\\Controllers\\Controller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreate\fP (Request $request)"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Controllers\\Auth\\NewPasswordController::create (Request $request)"
Display the password reset view\&. 
.SS "App\\Http\\Controllers\\Auth\\NewPasswordController::store (Request $request)"
Handle an incoming new password request\&.

.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP
Illuminate\\Validation\\ValidationException 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
