.TH "App\Models\Facility" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\Facility
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdonation\fP ()"
.br
.ti -1c
.RI "\fBdonationItem\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'facilities'"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\Facility::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'name',
        'description',
        'dimension',
        'material',
        'price',
        'amount',
        'status'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
