.TH "App\Models\Donee" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\Donee
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Models\\User\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdonations\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBApp\\Models\\User\fP
.in +1c
.ti -1c
.RI "\fBnewInstance\fP ($attributes=[], $exists=false)"
.br
.ti -1c
.RI "\fBnewFromBuilder\fP ($attributes=[], $connection=null)"
.br
.ti -1c
.RI "\fBuserProfile\fP ()"
.br
.ti -1c
.RI "\fBuserIdentity\fP ()"
.br
.ti -1c
.RI "\fBisVerified\fP ()"
.br
.ti -1c
.RI "\fBisAdmin\fP ()"
.br
.ti -1c
.RI "\fBrole\fP ()"
.br
.ti -1c
.RI "\fBroleName\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$guarded\fP"
.br
.in -1c

Protected Attributes inherited from \fBApp\\Models\\User\fP
.in +1c
.ti -1c
.RI "\fB$table\fP = 'users'"
.br
.ti -1c
.RI "\fB$guarded\fP"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.ti -1c
.RI "\fB$hidden\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBApp\\Models\\User\fP
.in +1c
.ti -1c
.RI "\fBcasts\fP ()"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\Donee::$guarded\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'type',
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
