.TH "App\Http\Controllers\Auth\AuthenticatedSessionController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers\Auth\AuthenticatedSessionController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Http\\Controllers\\Controller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (\fBLoginRequest\fP $request)"
.br
.ti -1c
.RI "\fBdestroy\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController::create ()"
Display the login view\&. 
.SS "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController::destroy (Request $request)"
Destroy an authenticated session\&. 
.SS "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController::store (\fBLoginRequest\fP $request)"
Handle an incoming authentication request\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
