.TH "App\Models\DoneeApplication" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\DoneeApplication
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBapplicant\fP ()"
.br
.ti -1c
.RI "\fBreviewer\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'donee_applications'"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\DoneeApplication::$fillable\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'status',
        'reviewed_at'
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
