.TH "App\Models\ProductDonation" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Models\ProductDonation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApp\\Models\\Donation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbooks\fP ()"
.br
.ti -1c
.RI "\fBfacilities\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBApp\\Models\\Donation\fP
.in +1c
.ti -1c
.RI "\fBcasts\fP ()"
.br
.ti -1c
.RI "\fBnewInstance\fP ($attributes=[], $exists=false)"
.br
.ti -1c
.RI "\fBnewFromBuilder\fP ($attributes=[], $connection=null)"
.br
.ti -1c
.RI "\fBinitiator\fP ()"
.br
.ti -1c
.RI "\fBreviewer\fP ()"
.br
.ti -1c
.RI "\fBdonors\fP ()"
.br
.ti -1c
.RI "\fBdonorDonations\fP ()"
.br
.ti -1c
.RI "\fBtype\fP ()"
.br
.ti -1c
.RI "\fBcategory\fP ()"
.br
.ti -1c
.RI "\fBtypeAttributes\fP ()"
.br
.ti -1c
.RI "\fBsetPending\fP (\fBUser\fP $user)"
.br
.ti -1c
.RI "\fBsetOnProgress\fP (\fBUser\fP $user)"
.br
.ti -1c
.RI "\fBsetDenied\fP (\fBUser\fP $user)"
.br
.ti -1c
.RI "\fBsetFinished\fP (\fBUser\fP $user)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$guarded\fP"
.br
.in -1c

Protected Attributes inherited from \fBApp\\Models\\Donation\fP
.in +1c
.ti -1c
.RI "\fB$table\fP = 'donations'"
.br
.ti -1c
.RI "\fB$guarded\fP"
.br
.ti -1c
.RI "\fB$fillable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "App\\Models\\ProductDonation::$guarded\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'type',
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
