.TH "md__r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- README 
.PP


.PP
\fR\fP
.PP

.PP
\fR\fP \fR\fP \fR\fP \fR\fP 
.SS "About Laravel"
Laravel is a web application framework with expressive, elegant syntax\&. We believe development must be an enjoyable and creative experience to be truly fulfilling\&. Laravel takes the pain out of development by easing common tasks used in many web projects, such as:

.PP
.IP "\(bu" 2
\fRSimple, fast routing engine\fP\&.
.IP "\(bu" 2
\fRPowerful dependency injection container\fP\&.
.IP "\(bu" 2
Multiple back-ends for \fRsession\fP and \fRcache\fP storage\&.
.IP "\(bu" 2
Expressive, intuitive \fRdatabase ORM\fP\&.
.IP "\(bu" 2
Database agnostic \fRschema migrations\fP\&.
.IP "\(bu" 2
\fRRobust background job processing\fP\&.
.IP "\(bu" 2
\fRReal-time event broadcasting\fP\&.
.PP

.PP
Laravel is accessible, powerful, and provides tools required for large, robust applications\&.
.SS "Learning Laravel"
Laravel has the most extensive and thorough \fRdocumentation\fP and video tutorial library of all modern web application frameworks, making it a breeze to get started with the framework\&.

.PP
You may also try the \fRLaravel Bootcamp\fP, where you will be guided through building a modern Laravel application from scratch\&.

.PP
If you don't feel like reading, \fRLaracasts\fP can help\&. Laracasts contains thousands of video tutorials on a range of topics including Laravel, modern PHP, unit testing, and JavaScript\&. Boost your skills by digging into our comprehensive video library\&.
.SS "Laravel Sponsors"
We would like to extend our thanks to the following sponsors for funding Laravel development\&. If you are interested in becoming a sponsor, please visit the \fRLaravel Partners program\fP\&.
.SS "Premium Partners"
.IP "\(bu" 2
\fB\fRVehikl\fP\fP
.IP "\(bu" 2
\fB\fRTighten Co\&.\fP\fP
.IP "\(bu" 2
\fB\fRWebReinvent\fP\fP
.IP "\(bu" 2
\fB\fRKirschbaum Development Group\fP\fP
.IP "\(bu" 2
\fB\fR64 Robots\fP\fP
.IP "\(bu" 2
\fB\fRCurotec\fP\fP
.IP "\(bu" 2
\fB\fRCyber-Duck\fP\fP
.IP "\(bu" 2
\fB\fRDevSquad\fP\fP
.IP "\(bu" 2
\fB\fRJump24\fP\fP
.IP "\(bu" 2
\fB\fRRedberry\fP\fP
.IP "\(bu" 2
\fB\fRActive Logic\fP\fP
.IP "\(bu" 2
\fB\fRbyte5\fP\fP
.IP "\(bu" 2
\fB\fROP\&.GG\fP\fP
.PP
.SS "Contributing"
Thank you for considering contributing to the Laravel framework! The contribution guide can be found in the \fRLaravel documentation\fP\&.
.SS "Code of Conduct"
In order to ensure that the Laravel community is welcoming to all, please review and abide by the \fRCode of Conduct\fP\&.
.SS "Security Vulnerabilities"
If you discover a security vulnerability within Laravel, please send an e-mail to Taylor Otwell via \fRtaylor@laravel\&.com\fP\&. All security vulnerabilities will be promptly addressed\&.
.SS "License"
The Laravel framework is open-sourced software licensed under the \fRMIT license\fP\&. 
